DROP SCHEMA IF EXISTS source CASCADE;
DROP SCHEMA IF EXISTS garbage CASCADE;
DROP SCHEMA IF EXISTS public CASCADE;

CREATE SCHEMA source;
CREATE SCHEMA garbage;
CREATE SCHEMA public;

CREATE EXTENSION pgcrypto;